/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package imas_software;

import static imas_software.filter_interface.header;
import java.util.HashMap;
import java.util.Stack;
import javax.swing.JScrollPane;

/**
 *
 * @author Esclender
 */
public class graphic_interface extends javax.swing.JPanel {

    /**
     * Creates new form graphic_interface
     */
    
    public static JScrollPane info_contain;
    public static Stack<Stack> data;
    private HashMap<Integer,String> options = new HashMap<>();
    
    public graphic_interface( JScrollPane container, Stack header, Stack datos) {
        initComponents();
        
        info_contain = container;
        data = datos;
        
        for(int i = 0; i < header.size(); i++){
            column_1.addItem((String) header.get(i));
            column_2.addItem((String) header.get(i));
            options.put(i, header.get(i).toString());
        }
        
        /**
        for(Object p: header){
            
            column_1.addItem((String) p);
            column_2.addItem((String) p);
        }
        **/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        info_container = new javax.swing.JPanel();
        column_1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        show_graphic = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        column_2 = new javax.swing.JComboBox<>();

        info_container.setBackground(new java.awt.Color(255, 255, 255));
        info_container.setForeground(new java.awt.Color(255, 255, 255));
        info_container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        column_1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                column_1ItemStateChanged(evt);
            }
        });
        column_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                column_1ActionPerformed(evt);
            }
        });
        info_container.add(column_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 100, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Columas a graficar");
        info_container.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Columna 1");
        info_container.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        show_graphic.setText("Graficar");
        show_graphic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_graphicActionPerformed(evt);
            }
        });
        info_container.add(show_graphic, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 100, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Columna 2");
        info_container.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        info_container.add(column_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(info_container, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(info_container, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void column_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_column_1ActionPerformed
        // TODO add your handling code here:
        System.out.println(column_1.getSelectedIndex());

        
        if(column_2.getItemCount() == column_1.getItemCount()){
            column_2.removeItem(column_1.getSelectedItem());
        }else{
            column_2.removeAllItems();
            for(int i = 0; i < options.size(); i++){
                if(i != column_1.getSelectedIndex()){
                    column_2.addItem(options.get(i));
                }
            }
        }
        
    }//GEN-LAST:event_column_1ActionPerformed

    private void show_graphicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_graphicActionPerformed
        // TODO add your handling code here:
            
            Stack selected_items = new Stack();
            
            for(Stack d: data){
                if(d.size() != 0 ){
                    int i1 = (int)  column_1.getSelectedIndex();
                    int i2 = (int)  column_2.getSelectedIndex();
                    Stack newStack = new Stack();
                    
                    newStack.push(d.get(i1));
                    newStack.push(d.get(i2));
                    

                    selected_items.push(newStack);
                }
                
            }
            
            show_graphics panel = new show_graphics(selected_items);
            panel.setSize(651,360);
            
            info_contain.removeAll();
            info_contain.add(panel);
            info_contain.revalidate();
            info_contain.repaint();
    }//GEN-LAST:event_show_graphicActionPerformed

    private void column_1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_column_1ItemStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_column_1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> column_1;
    private javax.swing.JComboBox<String> column_2;
    private javax.swing.JPanel info_container;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton show_graphic;
    // End of variables declaration//GEN-END:variables
}
