/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package imas_software;

import java.io.IOException;
import java.util.Stack;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esclender
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPrincipal
     * @throws java.io.IOException
     */
    public InterfazPrincipal() throws IOException {
        

        initComponents();/**[]**/
        
            IMAS_SOFTWARE Ex = new IMAS_SOFTWARE();
            Stack nuevo = Ex.LeerExcel();
            Stack Headers = Ex.LeerHeaders();
            
        
            show_excel panel = new show_excel(nuevo, Headers);
            panel.setSize(650,360);
            
            info_container.removeAll();
            info_container.add(panel);
            info_container.revalidate();
            info_container.repaint();
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit_menu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        options_menu = new javax.swing.JPanel();
        graphic_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        filter_button = new javax.swing.JButton();
        info_container = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_menu.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo_IMAS_.png"))); // NOI18N

        javax.swing.GroupLayout exit_menuLayout = new javax.swing.GroupLayout(exit_menu);
        exit_menu.setLayout(exit_menuLayout);
        exit_menuLayout.setHorizontalGroup(
            exit_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exit_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(654, Short.MAX_VALUE))
        );
        exit_menuLayout.setVerticalGroup(
            exit_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exit_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(exit_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        options_menu.setBackground(new java.awt.Color(153, 153, 153));

        graphic_button.setForeground(new java.awt.Color(51, 51, 51));
        graphic_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/graphic.png"))); // NOI18N
        graphic_button.setText("Graficar");
        graphic_button.setBorder(null);
        graphic_button.setBorderPainted(false);
        graphic_button.setContentAreaFilled(false);
        graphic_button.setDefaultCapable(false);
        graphic_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphic_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Opciones");

        filter_button.setForeground(new java.awt.Color(51, 51, 51));
        filter_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/filter_image.png"))); // NOI18N
        filter_button.setText("Filtrar");
        filter_button.setBorder(null);
        filter_button.setBorderPainted(false);
        filter_button.setContentAreaFilled(false);
        filter_button.setDefaultCapable(false);
        filter_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout options_menuLayout = new javax.swing.GroupLayout(options_menu);
        options_menu.setLayout(options_menuLayout);
        options_menuLayout.setHorizontalGroup(
            options_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(options_menuLayout.createSequentialGroup()
                .addGroup(options_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(options_menuLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(options_menuLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(graphic_button, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(options_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(options_menuLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(filter_button, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        options_menuLayout.setVerticalGroup(
            options_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(options_menuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(99, 99, 99)
                .addComponent(graphic_button, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(173, 173, 173))
            .addGroup(options_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(options_menuLayout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(filter_button, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addGap(244, 244, 244)))
        );

        getContentPane().add(options_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 410));

        info_container.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        getContentPane().add(info_container, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 650, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void graphic_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphic_buttonActionPerformed
        // TODO add your handling code here:
        try {
            IMAS_SOFTWARE Ex = new IMAS_SOFTWARE();
            Stack nuevo = Ex.LeerExcel();
            Stack headers = Ex.LeerHeaders();
            
            graphic_interface panel = new graphic_interface(info_container, headers,nuevo);
            panel.setSize(650,360);
            
            info_container.removeAll();
            info_container.add(panel);
            info_container.revalidate();
            info_container.repaint();
        } catch (IOException ex) {
            Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_graphic_buttonActionPerformed

    private void filter_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_buttonActionPerformed
        // TODO add your handling code here:
            try {
            IMAS_SOFTWARE Ex = new IMAS_SOFTWARE();
            Stack nuevo = Ex.LeerExcel();
            Stack headers = Ex.LeerHeaders();
            
            filter_interface panel = new filter_interface(headers,nuevo,info_container);
            panel.setSize(650,360);
            
            info_container.removeAll();
            info_container.add(panel);
            info_container.revalidate();
            info_container.repaint();
        } catch (IOException ex) {
            Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_filter_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazPrincipal().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel exit_menu;
    private javax.swing.JButton filter_button;
    private javax.swing.JButton graphic_button;
    private javax.swing.JScrollPane info_container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel options_menu;
    // End of variables declaration//GEN-END:variables
}
