/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package imas_software;

import java.io.IOException;
import java.util.Stack;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Esclender
 */
public class show_excel extends javax.swing.JPanel {

    /**
     * Creates new form show_excel
     * @throws java.io.IOException
     */
    public show_excel(Stack nuevo, Stack headers) throws IOException {
        initComponents();
        DefaultTableModel table = new DefaultTableModel();
        
        this.Headers(table, headers);
        this.MakeRows(table, nuevo);
        this.Sizes(headers);
        
        show_info.setModel(table);
        
    }
    
    public void MakeRows (DefaultTableModel table, Stack datos){
        for(int i = 0; i < datos.size(); i++){
            table.addRow((Vector<?>) datos.get(i));
        }
    }
    
    public void Headers (DefaultTableModel table, Stack datos) throws IOException {
        
        
        for (int i = 0; i < datos.size(); i++){
            table.addColumn(datos.get(i));
            
        }
        
        show_info.setModel(table);
        
    }
    
    
    public void Sizes(Stack datos){
        for (int i = 0; i < datos.size(); i++){
            show_info.getColumnModel().getColumn(i).setPreferredWidth(300);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        show_info = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        show_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        show_info.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        show_info.setMinimumSize(new java.awt.Dimension(300, 64));
        jScrollPane2.setViewportView(show_info);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable show_info;
    // End of variables declaration//GEN-END:variables
}
